### PR TITLE
Add test batch release stage 373

### PR DESCRIPTION
**Pull request by bausmeier**
Changes:

* Adds a RELEASED status to test batches.
* Adds logic for when a test batch can be closed or released.
* Moves the existing logic for creating deferrals, creating post donation counseling, and flagging components as unsafe to the release stage.
* Automatically release individual test samples when discrepancies are resolved and the test batch is released.

This was branched off of 350_duplicate_donors_api so that I could use the BloodTestService and to prevent conflicts.

### CODE REVIEW

**Comment by bausmeier** [comment]
@danfuterman Please review the changes in this range https://github.com/jembi/bsis/compare/603fda3cbd2dfed49b318764747c04795c8100d1...38a42e23d3457aed843bbe5badce265f22486410. They relate to updating component statuses at the correct time.

**Comment by danfuterman** [comment]
@bausmeier - I've run into an issue while testing this on my local instance. My guess is the issue is related to https://github.com/jembi/bsis/pull/361 (Pack type config #358).

To reproduce:
In my test batch I had 3 donations, two of those were for the same donor, and one of those was a `Did Not Bleed` donation (i.e. no test sample produced).
I was able to record TTI outcomes and confirmatory outcomes, but then I recorded the blood group serology outcomes, saved the form and was no longer able to access the test batch (i.e. it doesn't appear in the list of Open Test Batches).
Looking at the console output, my guess is that it's trying to apply the blood group serology outcomes to the donation that did not produce a test sample:

image

**Comment by bausmeier** [comment]
@danfuterman Well picked up, it should be fixed now. That exception was being thrown when adding the permissions to the test batch.

**Comment by danfuterman** [comment]
@bausmeier - tested and working well, thanks for the quick fix.
Since this PR includes some of the donor merging work, I'm going to try merge that PR into master first, and then I'll wrap up merging this PR.

**Comment by bausmeier** [comment]
Cool. I would like to have another look at this stuff if I find some time after I am done with my other tickets - just want to make sure that I haven't missed anything. So it's fine with me if this PR stays open for a while.

**Comment by danfuterman** [comment]
Closes #373.

**Comment by danfuterman** [comment]
@bausmeier - cool, that works for me, I'm still testing various scenarios for this PR - if we plan to merge by the end of the week that's fine.

I've run into a potential issue, need to look into it more to see if it is an issue and if it's caused by this PR:

I added a POS TTI outcome for DIN `8888889`, and released and closed the batch - the TTI Testing status appears as `TTI_UNSAFE`, but none of the components' statuses have been updated, and when I use the DIN in the labelling section, only the component that I manually discarded earlier in the process appears:

image

image

image

**Comment by danfuterman** [comment]
Tested on dev server (http://178.62.54.161/bsis/), but the release stage did not seem to appear. Not sure this is related to recent changes that have been merged into master and might be conflicting with the work done for this PR?

At this stage, the batch was ready to be released, but no indication on the UI of releasing a batch:
image

Then after recording all confirmatory outcomes, the release stage did not appear in the UI either, but the `Close Batch` appeared on the UI:

image

**Comment by bausmeier** [comment]
@danfuterman Have you tried doing a hard refresh? The links appear for me.

**Comment by danfuterman** [comment]
I also noticed a potential issue with the updating of Component Status - 

Using DIN 9000800 as an example, at this point in time, test outcomes had been entered in for this sample, with a POS tti outcome, but the batch had not been released, or closed off.

Before processing, the initial component still appeared as QUARANTINED (correct), but after processing, the resulting components appear as UNSAFE:

image

With the Test Batch Release, my understanding is that this status change should only be applicable/propagate after the batch has been released.

**Comment by danfuterman** [comment]
@bausmeier will retest again after clearing the cache.

**Comment by danfuterman** [comment]
@bausmeier Apologies, link appears now, will retest.

**Comment by danfuterman** [comment]
@bausmeier - retested, test batch working as expected, but component status issue still exists - 
 - To recreate:
  - Add a donation from an ineligible donor to a historical donation batch.
  - Open a test batch that includes that donation batch
  - Record initial TTI outcomes (all NEG outcomes)
  - Go to Component Processing, Record Components:
image
Initial component shows up as UNSAFE (correct).

  - Process components:
image

Two issues:
 - The new components' status has been changed from UNSAFE to a safe status (AVAILABLE)
 - The batch has not been released at this point - from my understanding, no new status should have been declared/known at this point in the workflow.

**Comment by bausmeier** [comment]
@danfuterman I have fixed the issues above. Please review https://github.com/jembi/bsis/compare/bc15c2942f87a1d0244b49fc99bd3f476b77470b...bb46330c04772a4fff1f12184eb4914ea60cecb4 and test on my dev server.

**Comment by danfuterman** [comment]
@bausmeier retested, original component status issue no longer occurs, but there is a new issue using the same workflow:

To recreate:

Add a donation from an ineligible donor to a historical donation batch.
image


Open a test batch that includes that donation batch
Record initial TTI outcomes (all NEG outcomes)

Go to Component Processing, Record Components, Initial component shows up as UNSAFE (correct).
image

Process components, resulting components are now flagged as QUARANTINED, rather than UNSAFE:
image

Record Test Results all NEG, Release Batch and Close Batch. Search for Components after this: the status remains as QUARANTINED:
image

i.e. the components seem to be stuck in a QUARANTINED state.

**Comment by bausmeier** [comment]
@danfuterman Please review bb46330c04772a4fff1f12184eb4914ea60cecb4...fa7b1ed1d0d536e5023677760dc0924f69c1b6cf. Released to my dev server.

@jonojhs If you have some time also please test for regressions in the component status updates. There seem to be lots of issues coming out of this.

**Comment by jonojhs** [comment]
@bausmeier certainly - will investigate just now

**Comment by danfuterman** [comment]
Thanks @bausmeier - the previous issue has been resolved with the new commits, but this seems to have impacted on another use case:

 - Add donation for suitable donor, initial components flagged as QUARANTINED (correct).
 - Record components - new components flagged as QUARANTINED (correct).
 - Add donation batch to test batch, record test outcomes (all NEG, no discrepancies). 
 - Release Batch. Components still flagged as QUARANTINED (should be AVAILABLE at this point).
 - Close Batch. Components still flagged as QUARANTINED (should be AVAILABLE at this point).
image

**Comment by bausmeier** [comment]
@danfuterman Hmm. I specifically tested that case, but I will try again and see if I can figure out what's wrong.

**Comment by bausmeier** [comment]
@danfuterman There definitely seems to be an issue here. The donations in the closed test batch have a TTI status of "Not Done". That shouldn't be possible.

**Comment by bausmeier** [comment]
@danfuterman I can't reproduce that on the dev server or locally.

My steps were:

1. Add 3 donors:
  * 2 eligible
  * 1 with a deferral
2. Add a donation batch marked as back entry.
3. Add 1 donation for each of the donors (components correctly set to QUARANTINED for eligible donors and UNSAFE for deferred donor).
4. Close the donation batch.
5. Record components (new components correctly set to QUARANTINED for eligible donors and UNSAFE for deferred donor).
6. Create a test batch.
7. Record TTI results:
  * All negative for the first eligible donor
  * HIV POS with POS confirmations for the second eligible donor.
  * All negative for the deferred donor.
8. Record and confirm blood group serology tests for all donors.
9. Release test batch.
10. Close test batch.

The outcomes were (as expected):

1. Components for eligible donor with negative results all set to AVAILABLE.
2. Components for eligible donor with positive TTI results all set to UNSAFE.
3. Components for deferred donor with negative results set to UNSAFE.

The eligible donor with negative results should cover the scenario you described above.

**Comment by danfuterman** [comment]
Thanks @bausmeier, I'll test some more, but for clarity on how my steps differed from yours above (in case there's a nuance in there somewhere that's related to the issue):

 - The eligible donor's donation was added to a regular donation batch (i.e. not an historical batch)
 - Components were recorded after opening the test batch (but before any initial outcomes were recorded).
 - There were no POS TTI outcomes recorded, so the confirmatory TTI outcomes step was never triggered.

**Comment by danfuterman** [comment]
Looking at the fact that the donation's TTI status were all marked as `Not Done`, my feeling is that the issue might be related to the 3rd point above - i.e. if the confirmatory TTI outcomes step is never triggered (i.e. no tests require further confirmatory outcomes), perhaps the TTI status is never updated.

**Comment by bausmeier** [comment]
@danfuterman Tested again with a regular donation batch, components recorded in the order you described, and no POS outcomes. Still couldn't reproduce it.

**Comment by bausmeier** [comment]
@danfuterman Okay managed to reproduce it now by confirming the blood group serology results after releasing the test batch.

**Comment by bausmeier** [comment]
@jonojhs @danfuterman Please test.

I fixed the issue where components were stuck as QUARANTINED after the test batch had been released, and the issue were the displayed TTI status for donations in the test batch was not updated from Not Done until the batch was released.

**Comment by danfuterman** [comment]
@bausmeier tested - only one issue, and it's probably outside of the scope of this issue, but noting it here for now - need to do further testing.

I have a component flagged as UNSAFE that came from an ineligble donation in a historical donation batch. Following testing, the component is still correctly labelled as UNSAFE, but the issue is when I scan in the DIN in the labelling section, it appears that the component is showing up as 'ready to be labelled' - and I'm able to print a pack label for that component.

image

image

**Comment by bausmeier** [comment]
@danfuterman I refactored the labelling logic to handle the case above. Please re-test.

**Comment by danfuterman** [comment]
:+1: Retested, issue resolved.

**Pull request merged**
