### PR TITLE
307 manage donation types

### PR DESCRIPTION
**Pull request by debonair**
@danfuterman please review

### CODE REVIEW

**Comment by debonair** [comment]
@danfuterman please review

**Comment by danfuterman** [comment]
@debonair - Works as expected, but theres an issue with changing `getAllDonationTypes()` - this method is used in places like CollectedSampleController - `m.put("donationTypes", donorTypeRepository.getAllDonationTypes());` - when used in this context, the types that have been flagged as `isDeleted` should not appear in the return list. I'd suggest updating the repository method to include a boolean `includeDeleted` search flag that gives the option to include those or not, and then refactor existing uses of this method to include that flag.

**Comment by debonair** [comment]
@danfuterman I have included the includeDeleted flag, the default behaviour is not to include deleted lest you set the flag to true

**Comment by danfuterman** [comment]
Closes #307

**Pull request merged**
