### PR TITLE
BSIS-496 Save all test outcomes on one single call for 1st entry, re-entry and resolve ambiguous blood type

### PR DESCRIPTION
**Pull request by lauravignoli**
Please see associated bsis-frontend PR: https://github.com/jembi/bsis-frontend/pull/400

### CODE REVIEW

**Comment by timler** [comment]
Out of interest it takes 10.11 s to save 240 test outcomes (using the single post) and 3.41 s to execute the search endpoint which is used when loading the page.

**Comment by danfuterman** [comment]
@timler Is it easy/quick to reproduce that prior to the single entry changes, as a point of comparison in performance?

**Comment by timler** [comment]
@danfuterman I will reproduce with the multiple calls as soon as I'm finished the current review.  But, to confirm, the change wasn't to improve performance (at least so much) - it was to avoid results from one donation failing to save and leaving the user in an unknown state.

**Comment by danfuterman** [comment]
Thanks @timler, noted - what I'm really looking for is a comparison to check that the new changes haven't decreased performance.

**Comment by timler** [comment]
@danfuterman Ah yes - thanks for making that clear. With a number like 10s, it would be important to check we didn't make the situation worse. 

Luckily I can say we didn't. It's a little harder to get an exact number, but the saves took between 4ms and 11.78s to execute. The reason for the big disparity is that they executed in batches and had to wait. In total it took over 12s for all requests to complete.

**Comment by timler** [comment]
Also, the reason why the save takes so long to execute is that the BloodTestingRuleEngine is run twice. See this code: https://github.com/jembi/bsis/blob/master/src/service/BloodTestsService.java#L84-L107 (method saveBloodTests in BloodTestsService)

**Comment by danfuterman** [comment]
Thanks @timler, happy with that - as long as you're confident this hasn't impacted on performance, I don't need exact numbers.

**Pull request merged**
