### PR TITLE
410 edit confirmed test results

### LINKED ISSUE #410: Confirmed test results cannot be edited
Follow on from #408

See frontend issue here: https://github.com/jembi/bsis-frontend/issues/274

See part 2
> 1. Record ABO type ie. A+ and Confirm (works as expected) 
> 2. Record Results again for that same donation Change the Blood group or RHesus factor, 
> 3. The blood group type is listed as a Complete Match (even though changed from A+ to A-), however I would assume that this would be an incomplete match as the blood group has changed after being confirmed, it should raise a flag or something

To solve this issue, a new rule related to the Test Batch modification and deletion rules should be added.

The rule states:
 * The user cannot edit/update test outcomes once confirmatory test outcomes for that sample have been added

### PR DESCRIPTION
**Pull request by timler**
closes #410 

Note that this branch was created from 380_test_batch_update_delete

### CODE REVIEW

**Comment by timler** [comment]
Commit to review is 66ee84d338fe07857f731695626438eef6234407

**Comment by timler** [comment]
@bausmeier Please can you review when you get a chance? I've linked to the commits to review above because I branched off the test batches branch.

**Comment by timler** [comment]
@danfuterman I'm not sure I got the constraint checker right. Could you review it for me please. See: https://github.com/jembi/bsis/blob/410_edit_confirmed_test_results/src/service/BloodTestResultConstraintChecker.java

**Comment by bausmeier** [comment]
@timler Looks good to me. The only feedback that I have is that `BloodTestResultConstraintChecker#canEdit` is quite difficult to follow. The else statements after the returns aren't necessary so maybe you could get rid of those and put in some blank lines to separate each branch of the logic? Up to you though, just personal preference.

Please just merge in the latest master and resolve the conflicts. Then I will give it one last test.

**Comment by timler** [comment]
@danfuterman I have implemented the changes we discussed this afternoon. 

@jonojhs please take note of the following

For TTI tests
 - If screening test NEG, it can be edited until the batch and donation are released
 - If screening test POS, it can be edited until one/both of the repeat tests have been recorded
 - If repeat tests require additional confirmatory test, they can be edited until the confirmatory test outcome has been recorded

For Serology/BloodTyping tests
 - It's currently not possible to disable editing of Blood Serology (blood typing) tests. This is because the confirmation of the tests is not recorded and as a result we can't see the difference between tests that didn't need confirmation and tests that had confirmation.

You can take a look on my dev server - http://178.62.18.215/bsis/#/viewTestBatch/3

**Comment by jonojhs** [comment]
@timler So far is looking pretty good :) I'm just adding my findings here - subject to change and may not actually be an issue, but please have a look. 

(Unsure if following is an issue or desired functionality)
 if 2 donations are recorded for a donor (double pack donation and a test only etc) and you record a different blood type for the test only donation,  Upon confirming the amibigous test for the drypack it displays the test result from the confirmed donation

//0000042 (double pack) and 0000029 (Dry pack) belong to same donor 000013
//Note the drypack ambigous test result (A-) because the double pack donation was confirmed as A+ 
image

//when viewing to confirm the ambigious test result for the Drypack it displays the 0000042 (double pack) confirmed test result (A+) and not the result from the original drypack test (A-)
image

**Comment by danfuterman** [comment]
To confirm - issue raised by @jonojhs is out of scope for this, and is an issue with the bloodtyping algorithm.

**Comment by timler** [comment]
New code to review:
 - Recent changes: 719dc0f...83f1afc

Note: I have replaced the code on my dev server, so it is no longer possible to preview this branch.

**Comment by danfuterman** [comment]
@bausmeier Just checking if there are any additional comments following the commits that were pushed after your last review. Great if there aren't - I'll be looking at merging this and #401 in during the course of the day.

**Comment by bausmeier** [comment]
@danfuterman No more comments. I think that this is ready to be merged once 401 is in.

**Pull request merged**
