### PR TITLE
BSIS-270: Remove Weak D Test in Serology Testing

### PR DESCRIPTION
**Pull request by timler**
See JIRA ticket: https://jembiprojects.jira.com/browse/BSIS-270

### CODE REVIEW

**Comment by timler** [comment]
@bausmeier @danfuterman Not sure how to best handle this problem. The issue is that there is a bug in `db-fix-ids.xml` with the foreign key reference in BloodTests_WorksheetTypes. If you have an existing database you will need the bug to be fixed before the changeset to delete the Weak D blood test. If you have a new database you'll need the fix to be applied after the file `db-fix-ids.xml`.

Since removing the Weak D BloodTest is to do with data, I put the changeset (and fix) in `db-data-lbts.xml`.

To make it work on existing and new database, I'll need to do one of the following:
 1. Create a new liquibase changeset file that executes after all the others - this file should contain the changeset to delete the Weak D test. A changeset to fix the foreign key bug can be put in the file or in `db-fix-ids.xml`.
 2. Copy and paste a changeset to fix the foreign key reference in both `db-data-lbts.xml` and `db-fix-ids.xml`. I'd use different ids and changesets to ensure they aren't executed twice.

I had this same problem the other day and ended up adding a new changeset to `db-after-data,xml` (instead of to `db-config.xml`).  I think this will be a problem we'll face in the future.

**Comment by timler** [comment]
So not sure if this is the best solution, but I found a liquibase precondition `changeSetExecuted` that you can use to check if a changeset has run already.

**Comment by bausmeier** [comment]
The solution seems reasonable to me.

**Comment by danfuterman** [comment]
@timler - Agreed, the solution seems appropriate - I'd just like to follow up on the point that you raised to consider if this could be a recurring issue that we face.
Would you consider this solution a standard practice to follow for the case where we face the same issue down the line? Regarding your suggestion to 'Create a new liquibase changeset file that executes after all the others' - would this still be useful, or is this no longer needed with the latest solution? We want to limit the number of changeset files that we add to the system, but if it's going to save a lot of time/effort down the line (if this is going to be a recurring problem), I'd like to discuss the need for this. If it's not needed anymore, I'm happy with this as is.

**Comment by bausmeier** [comment]
Tested on a clean database and an existing one and it works as expected.

**Comment by timler** [comment]
An issue just emerged while @debonair was updating a dev server.

liquibase error
```
SEVERE 2016/03/03 3:00 PM:liquibase: Change Set ./liquibase/db-data-lbts.xml::20160301-1124::timler failed.  Error: Error executing SQL ALTER TABLE `BloodTest_WorksheetType` DROP FOREIGN KEY `fk_BloodTest_WorksheetType_worksheetTypes_id`: Can't DROP 'fk_BloodTest_WorksheetType_worksheetTypes_id'; check that column/key exists
liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE `BloodTest_WorksheetType` DROP FOREIGN KEY `fk_BloodTest_WorksheetType_worksheetTypes_id`: Can't DROP 'fk_BloodTest_WorksheetType_worksheetTypes_id'; check that column/key exists
```

from a database, dump:
```
DROP TABLE IF EXISTS `BloodTest_WorksheetType`;
CREATE TABLE `BloodTest_WorksheetType` (
  `bloodTests_id` bigint(20) NOT NULL DEFAULT '0',
  `worksheetTypes_id` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`bloodTests_id`,`worksheetTypes_id`),
  KEY `fk_BloodTest_WorksheetType_BloodTest` (`bloodTests_id`) USING BTREE,
  KEY `fk_BloodTest_WorksheetType_worksheetTypes_id` (`worksheetTypes_id`) USING BTREE,
  CONSTRAINT `BloodTest_WorksheetType_ibfk_1` FOREIGN KEY (`bloodTests_id`) REFERENCES `BloodTest` (`id`),
  CONSTRAINT `BloodTest_WorksheetType_ibfk_2` FOREIGN KEY (`worksheetTypes_id`) REFERENCES `BloodTest` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

The issue is that the constraints are not named as expected, but `BloodTest_WorksheetType_ibfk_2`

**Pull request merged**
