### PR TITLE
Update due to donate date when updating or deleting donations

### LINKED ISSUE #426: Ensure donor fields are updated when donation is updated or voided
Editing or voiding a donation should also update or revert the 'num. donations' and 'date to donate' fields of the associated donor.

### PR DESCRIPTION
**Pull request by bausmeier**
Updates the donor's due to donate date to the latest date when a donation is updated. This has to consider all of the donations since the current due to donate date may or may not be related to the donation being updated or deleted.

Closes #426.

### CODE REVIEW

**Comment by bausmeier** [comment]
@danfuterman Please review. Also note that I added a test for the new query but had to ignore it because I couldn't get the query to run with HSQLDB. I tested that it does work with MySQL though.

**Comment by bausmeier** [comment]
@jonojhs Please take a look at this on my dev server as well.

**Comment by danfuterman** [comment]
@bausmeier - If I add a donation with Pack Type 'Test Only', the Due To Donate date is not what I'd expect:
image

**Comment by bausmeier** [comment]
@danfuterman What would you expect to see in that case?

**Comment by danfuterman** [comment]
Oh wait, sorry, I was using an existing donation batch that was opened a week ago (on the 23/11/15), so that does make sense.

**Comment by danfuterman** [comment]
I thought I had added it to a new batch that was created today.

**Comment by bausmeier** [comment]
@danfuterman Ah ok. Yeah it just adds the period between donations (in this case 0) to the donation date.

**Comment by danfuterman** [comment]
Cool, happy with the approach (where it considers all donations), and testing done.
@jonojhs any feedback before I merge this in?

**Pull request merged**
