### PR TITLE
BSIS-342: As a serology testing staff user I want to be able to enter a repeat test for ABO and Rh for a first time donor.

### PR DESCRIPTION
**Pull request by timler**
See user story in JIRA: https://jembiprojects.jira.com/browse/BSIS-342

### CODE REVIEW

**Comment by timler** [comment]
@danfuterman, do you mind taking a look at commit  5599b7a? Specifically the dbunit test BloodTestingRuleEngineTest and the resulting statuses after running the rules engine. What I discovered (again) is that the BloodTypingMatchStatus will only be marked as COMPLETE when the donor ABO/Rh matches the donation ABO/Rh. This only happens after the confirmation checkbox is ticked.

**Comment by danfuterman** [comment]
@timler - looks good to me, and the two dbunit tests make sense. My only suggestion is that it might be useful (not sure if this is already covered by the existing dbunit tests) to also have similar unit tests for repeat donors - to be able to assert that bloodtypingstatus/bloodtypingmatchstatus/pending tests are set as expected.

**Comment by timler** [comment]
@danfuterman Thanks for the response. I did a little audit on the Rules Engine and test (see commit 6dc1d25). I believe that there is a good spread of tests and I have put a comment and changed the test method names to make it clear what the tests are testing.

While I did the audit I saw that there are a few lines in the rules engine that can never be reached. The worst is for the BloodMatchStatus flag which can only ever be NO_MATCH or COMPLETE. (It can't be AMBIGUOUS or PENDING_TESTS). The former because we only retrieve the latest test resuslt for each BloodTest and also because there is only 1 rule for ABO and 1 for Rh (the new Abo/Rh repeat tests are not separate rules). The latter is never reached because it's not possible to have 0 Abo or Rh changes and pending Abo or Rh test.

I also found a bug in my code where the BloodMatchStatus was not set correctly (it was set to NO_MATCH when it actually was COMPLETE) because the exception for pending ABO and Rh tests wasn't applied before setting the BloodMatchStatus. I just re-ordered the method calls.

**Comment by danfuterman** [comment]
Thanks for breaking those issues out @timler - happy with the recent changes - LGTM.

**Comment by timler** [comment]
Reviewing 6f011a8~...ff7c6b8

**Pull request merged**
