### PR TITLE
Add labelling fields to component types #238

### PR DESCRIPTION
**Pull request by danfuterman**
See #238
Replaces PR #240

### CODE REVIEW

**Comment by danfuterman** [comment]
@srikanthmalyala - there doesn't seem to be any way to add/update these properties using the API?
Also, I'm not sure that the ViewModel is the best place to set the full text for Storage and Transport info, e.g.:

```
public String getTransportInformation(){
        final String DEGREECELSIUS  = "\u2103";
        return "transport at " + productType.getLowTransportTemperature()+ DEGREECELSIUS+ " to "
                + productType.getHighTransportTemperature()+ DEGREECELSIUS; 
                
  }
```

With this method, the initial text (when the min,max values are null) is:
```
    "storageInformation": "store at null℃ to null℃",
    "transportInformation": "transport at null℃ to null℃",
```
I think it could be cleaner to just work with the two min/max range values, and rather set the full text "Transport at ..." at the point where the pack label ZPL is generated.

**Comment by srikanthmalyala** [comment]
@danfuterman  These properties are tied to the component type, so POST componentType can be used to update these properties. Yeah it could be more cleaner to append the strings to temperature values while generating pack label rather in view models

**Comment by danfuterman** [comment]
But they don't appear in the backingForm do they? When I run `PUT /componenttypes/{id}` I get the error:

```
"Could not read JSON: Unrecognized field \"preparation\" (class backingform.ComponentTypeBackingForm)
```

**Comment by srikanthmalyala** [comment]
Yeah The fields are not defined in ComponentTypeBackingForm yet , Actually There is no backingform existing for product type in this issue but In master branch it exists. so I will branch off master to fix this issue.

**Comment by danfuterman** [comment]
I've merged master branch into this branch, so it should be available now.

**Comment by srikanthmalyala** [comment]
Thanks

**Pull request merged**
