### PR TITLE
Refacator locations

### PR DESCRIPTION
**Pull request by debonair**
This pull request works with https://github.com/jembi/bsis-frontend/issues/194

### CODE REVIEW

**Comment by danfuterman** [comment]
@debonair Please link to an issue.

**Comment by danfuterman** [comment]
Venues that have been flagged as disabled are showing up in the dropdown lists when I create a new Donation Batch, or specify the Donor's venue when adding/editing a donor.

**Comment by debonair** [comment]
@danfuterman I mis-understood the requirements then, does reverting this commit does reverting the last commit fix the issue, because I added these deliberately and disabled them in the dropdown do that you cannot select the item.

**Comment by danfuterman** [comment]
From the spec:
 - "if a venue is flagged as disabled, it still appears in this table, but does not appear in venue dropdowns elsewhere"
 - This is standard behaviour, as with all the other Manage Settings sections (deferral reasons, discard reasons, donation types, pack types etc.) - the behaviour here should be the same, no different to how the others work - if it's been flagged as disabled, it shouldn't appear in dropdown lists.

**Comment by debonair** [comment]
@danfuterman I have reverted the changes that caused the issue.

**Comment by danfuterman** [comment]
Closes #364

**Pull request merged**
