### PR TITLE
422 deferral reason default durations

### LINKED ISSUE #422: Add Deferral Reason default durations

### PR DESCRIPTION
**Pull request by danfuterman**
Closes #422

### CODE REVIEW

**Comment by danfuterman** [comment]
Uploaded to staging server http://95.85.19.213/bsis/.
Please review @jonojhs @bausmeier

**Comment by bausmeier** [comment]
:+1:

**Comment by jonojhs** [comment]
@danfuterman Looks good :+1:  - just a query regarding the TTI deferral duration when adding a manual deferral vs  an automated TTI deferral. 
The dates differ (manual)  01/01/2100 vs  (Automated) 31/12/2099 . Not really an issue, but just concerned that perhaps different date formats are being used ?

**Comment by bausmeier** [comment]
@jonojhs That's timezone related. The automated deferrals are created using the server's timezone and the manual deferrals use your timezone.

**Comment by jonojhs** [comment]
@bausmeier Cool thanks for the clarification, encountered a few cases where this has occured.

**Pull request merged**
