### PR TITLE
Modify search endpoint

### LINKED ISSUE #404: Update Recent Donation Batches View and Search
Currrently, the Recent Donation Batches view shows a list of recently closed batches, but this should be updated to include the following:

- Search by Venue
- Search by Batch date (created date)

For an example of this, refer to the Post Donation Counselling form:

image

The difference here is that the page should be preloaded with the following values:
 - Venue - Any Venue
 - Batch date - the past 7 days

The user can then change these values in the form to update the results shown in the table.

### PR DESCRIPTION
**Pull request by debonair**
@bausmeier please review, closes #404

### CODE REVIEW

**Comment by bausmeier** [comment]
@debonair Please add the missing test cases as we discussed.

**Comment by debonair** [comment]
@bausmeier added the test case

**Comment by bausmeier** [comment]
@debonair Your test isn't actually testing anything. If I take either or both of the date conditions out of the query the test still passes. There should be donation batches in the test fixture which fall outside of the date range that you are testing with to ensure that they are not returned.

**Comment by bausmeier** [comment]
Please also make sure that you remove any unused imports e.g. StringUtils in DonationBatchRepository.

**Comment by debonair** [comment]
@bausmeier please review

**Comment by bausmeier** [comment]
@debonair Cool, the test is useful now. Just left some minor comments.

**Comment by bausmeier** [comment]
LGTM, @danfuterman please do a final review.

**Comment by danfuterman** [comment]
@debonair is the latest version of this task on your dev server?
If so, the following requirement does not appear to have been addressed:

The page should be preloaded with the following values:
 - Batch date - the past 7 days

Currently, `Any Date` is selected by default, and the initial query on page load appears to load every donation batch from any date.

**Comment by danfuterman** [comment]
@debonair - the `Clear` button on the search form has no effect on the `Venues` input.

**Comment by debonair** [comment]
@danfuterman right, am looking into those 2 issues you pointed out.

**Pull request merged**
