### PR TITLE
385 refactor out donor code

### LINKED ISSUE #385: Refactor out donor code functionality
Donor code functionality has been replaced by specific functionality such as Adverse events, post donation counselling, and automated deferrals. This task consists of refactoring out the Donor Codes backend code:

 - Remove legacy code
 - Ensure nothing impacted
 - Use Liquibase scripts to remove tables
 - Compile and test (with description of what was tested and passed).

See the following for previous work on Donor Codes:

Add Donor Codes functionality: #136 (PR #169)
Refactor Code to make use of Donor Codes (NB. THIS IS INFORMATIONAL - THESE CHANGES WERE NEVER MERGED INTO MASTER): #173 (PR #199).

### PR DESCRIPTION
**Pull request by debonair**
closes #385

### CODE REVIEW

**Comment by debonair** [comment]
@danfuterman @bausmeier what is the best way to get rid of the Donor Code tables? should I roll back the changeset that created them or should I make a new change set to remove them?

**Comment by bausmeier** [comment]
@debonair The idea is to not alter any existing changesets, but I know that we have been doing this in some cases where Daniel wanted the reference to be removed entirely. I'm not sure if this is one of those cases. I think that would be okay for now, but after the next release I think we should stop doing it.

**Comment by danfuterman** [comment]
We're no longer altering changesets, so this would need to be done in a new changeset.

**Comment by debonair** [comment]
@bausmeier @danfuterman please review

**Comment by danfuterman** [comment]
@debonair - I don't see any refactoring/removal of Donor Code related classes and methods here, just a liquibase changeset?
Also, It looks like the changeset has been added to the middle of the file, rather than at the end of the file.

**Comment by debonair** [comment]
@danfuterman look at the whole PR, the classes were removed in a previous commit

**Comment by debonair** [comment]
@danfuterman I can move the changeset to the end of the file, however I thought that it would be better to put it close to where the original changest was done.

**Comment by danfuterman** [comment]
Okay cool, I was just looking at the most recent commit then. With more devs adding to the liquibase changesets, it's better if they are ordered by date/timestamp, rather than grouped by relevance, so I'd suggest moving it to the end.

**Comment by danfuterman** [comment]
@bausmeier Please review.

**Pull request merged**
