### PR TITLE
Add general config for creating initial components

### LINKED ISSUE #381: Configuration to turn off production of initial components
Currently, the system can be set up in such a way that the component processing, labelling and inventory  management features are not accessible. Currently, when a donation is added, initial components are automatically created according to the pack type that was selected in the donation. However, in the case where components are not managed in the system, it would be better to switch this off, and not create any initial component. This needs to be a configurable option, making use of a general config property.

### PR DESCRIPTION
**Pull request by bausmeier**
Adds a general config property that can be used to disable the creation
of initial components in the case that the components are not managed by
the system.

Closes #381.

### CODE REVIEW

**Comment by bausmeier** [comment]
@danfuterman Please review on my dev server.

**Comment by danfuterman** [comment]
@bausmeier - working as expected, the only issue I can see is with regards to labelling - I'd say this is outside of the scope of this task, but it'd be great to resolve it here if possible. The current way this is handled in labelling is on a donation DIN level, rather than a component DIN level. The result is that scanning a DIN where no components were produced results in a poor end-user response (no appropriate message displayed):

image

There is a distinction between this response and scanning a DIN that does not exist at all:
image

**Comment by bausmeier** [comment]
@danfuterman I opened another PR for the improvement that you mentioned: https://github.com/jembi/bsis-frontend/issues/241.

**Comment by bausmeier** [comment]
@jonojhs Please test this and the other referenced PR (https://github.com/jembi/bsis-frontend/pull/241).

**Comment by jonojhs** [comment]
@bausmeier Confirmed working as expected 

-No Components produced at donation level according to boolean setting of initial components :+1: 
-Message to display no components for donation in Labelling :+1:

**Pull request merged**
