### PR TITLE
379 update delete donationbatch

### LINKED ISSUE #379: Donation Batches – implement modification and deletion rules
Currently, a user can add a Donation Batch, but they cannot edit, delete or reopen the batch. The aim of this task is to add this functionality, and ensure the rules associated with this are in place.

-	Can I delete a donation batch if no donations have been added?
  -	Yes
  -	Can I Close a Donation batch if no donations have been added?
   -	No, it must be deleted rather
-	Can I edit the Panel and Date of a donation batch before any donations have been added?
  -	Yes
  -	Yes, and you can also edit the Panel and Date of a donation batch AFTER donations have been added
   -	Implication: the Panel & Date of the donations (and initial components) also has to be updated
     -	Consideration – only create initial components when batch is closed (avoids having to change creation dates of initial components)
-	Can I re-open a donation batch?
  -	Yes, immediately after
  -	Can I reopen a donation batch after it has been assigned to a test batch?
   -	No
  -	Can I edit existing donations when I reopen a batch?
   -	Yes
  -	Can I edit the Panel & Date of a donation batch when I reopen a batch?
   -	Yes
-	Can I add/edit the donor assessment fields (and add an adverse event) in a donation once the donation batch has been closed (and also after it’s been added to a test batch)? 
  -	i.e. What can I edit in a donation after the donation batch has been closed?
   -	Yes - adverse events, donor assessment fields, and comments

### PR DESCRIPTION
**Pull request by timler**
closes #379

### CODE REVIEW

**Comment by timler** [comment]
@danfuterman This task is finished and ready to merge

**Comment by bausmeier** [comment]
@timler Please add tests for DonationBatchViewModelFactory and DonationBatchConstraintChecker.

**Comment by timler** [comment]
@bausmeier Added tests as requested. See caafe29

**Comment by bausmeier** [comment]
@timler Looks good to me. Please just merge in the latest master and resolve the conflicts.

@danfuterman Ready for final review.

**Comment by timler** [comment]
@bausmeier @danfuterman I have merged in master.

**Pull request merged**
