### PR TITLE
Donor eligibility rules

### LINKED ISSUE #382: Update Donor Eligibility Rules
@bausmeier - Final description to follow, I need to bring together the final feedback from multiple sources into a clear description.

### PR DESCRIPTION
**Pull request by bausmeier**
Changes:

* Allows donation batches to be marked as back entry, which bypasses donor eligibility checks.
* Blocks donations from being added in the following cases:
  1. The period between donations has not passed for a previous donation.
  2. The donor has a deferral which is currently in effect.

The rule to block adding of donations based on donor age will be implemented as a warning in the frontend. This will allow clinic staff to use their discretion when deciding whether or not a donor can donate based on their age.

Closes #382.

### CODE REVIEW

**Comment by bausmeier** [comment]
@danfuterman @jonojhs Please review on my dev server.

**Comment by jonojhs** [comment]
@bausmeier Do we want to change the error message for when the donor eligibilty is in effect for the dates between donations ? @danfuterman what do you propose ?

image

**Comment by bausmeier** [comment]
It should probably say something like "Donor is not eligible to donate" instead, but I don't think we should specify why. As far as I understand it we don't want to show that the donor is deferred on this screen if that is the case. That is currently the only other rule for donor eligibility so if we specify the reason that the donor is ineligible in this case the user would be able to infer the reason in the other case.

**Comment by lindajembi** [comment]
Yes. Should just say something like Do not bleed.

On Tuesday, 3 November 2015, Brett Ausmeier <notifications@github.com>
wrote:

> It should probably say something like "Donor is not eligible to donate"
> instead, but I don't think we should specify why. As far as I understand it
> we don't want to show that the donor is deferred on this screen if that is
> the case. That is currently the only other rule for donor eligibility so if
> we specify the reason that the donor is ineligible in this case the user
> would be able to infer the reason in the other case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jembi/bsis/pull/400#issuecomment-153287782>.
>


-- 
Kind regards,
Linda

-----------------------------------------------------------------------------
Linda Taylor
Jembi Health Systems- Technical Project Coordinator
Skype: linda.jembi
linda.taylor@jembi.org <linda@jembi.org>
http://www.jembi.org

E-MAIL DISCLAIMER:
This e-mail contains proprietary and confidential information some or all
of which may be legally privileged. It is for the intended recipient only.
If an addressing or transmission error has misdirected this e-mail, please
notify the author by replying to this e-mail and then deleting same. If you
are not the intended recipient you must not use, disclose, distribute,
copy, print or rely on this e-mail. Jembi Health Systems NPO, its
subsidiaries and associated companies is not liable for the security of
information sent by e-mail and accepts no liability of whatsoever nature
for any loss, damage or expense resulting, directly or indirectly, from the
access of this e-mail or any attachments hereto.

**Comment by danfuterman** [comment]
Agreed.

**Comment by jonojhs** [comment]
From what I can see there should be 1 error message

Error Adding Donation 
*Do not bleed donor

Anything else should be resolved on the front end validation (User entering in data that the system does not accept)

Note below that the message says there is something wrong with the inputs, there is nothing wrong with the inputs, the donor is deferred

image

**Pull request merged**
