### PR TITLE
Add canEditDate permission

### LINKED ISSUE #427: Add rule to donation batches on updating batch date
Add rule to donation batches on updating batch date - the date cannot be edited if 1 or more donations have been added to the batch.

### PR DESCRIPTION
**Pull request by bausmeier**
Add canEditDate permission which is set based on whether or not there are donations in the batch.

Closes #427.

### CODE REVIEW

**Comment by bausmeier** [comment]
@danfuterman @jonojhs Please review and test on my dev server.

**Comment by danfuterman** [comment]
@bausmeier - Looks good, one minor issue - 

Added a donation batch. Edited the batch, changed the date. Added a donation to the batch. Edited the batch, the date field was disabled, but also highlighted in red, suggesting an issue:
image

Testing further to see if I can recreate this again.

**Comment by jonojhs** [comment]
@bausmeier  @danfuterman can confirm I have recreated that issue.

**Comment by jonojhs** [comment]
@bausmeier confirmed fixed :100:

**Pull request merged**
