### PR TITLE
Update deployment scripts

### PR DESCRIPTION
**Pull request by bausmeier**

### CODE REVIEW

**Comment by bausmeier** [comment]
@danfuterman Please review.

**Comment by danfuterman** [comment]
@bausmeier - The deployment update scripts have been removed, but haven't been replaced with a new bash update script. How do you see this working - i.e. after the initial installation, is there a process to update the server to the latest version of BSIS? 

The same applies to https://github.com/jembi/bsis-frontend/pull/213.

**Comment by bausmeier** [comment]
You can just run the bash script again. Also, if you want to deploy a different branch you can just pass the branch name as the first argument to the script.

**Comment by danfuterman** [comment]
So I think it's good that you can just run the bash script again, but do you think it's worth having a second script that doesn't go through the installation and setup steps? For practical use, if I'm in the process of working on an issue, and need to quickly push the most recent changes of my working branch to my dev server, being forced to run `sudo apt-get update` and go through the installation and setup steps slows this process down quite a bit. For something like the staging and demo servers, which only get updated when there are new changes to master, this isn't really an issue, but for the dev servers, I think it would be useful to have a quick way (i.e. using scripts) to push the latest changes of a working branch up.

**Comment by bausmeier** [comment]
@danfuterman On the dev servers the first few steps take less than 10 seconds when I run them for the second time. Comparing this to the amount of time the build takes I would say that having a separate update script wouldn't be very valuable.

**Comment by bausmeier** [comment]
@danfuterman I see that my comment above is not true for the frontend scripts. Maybe an update script would be worthwhile there.

**Comment by danfuterman** [comment]
For the backend script, I had to run this as `sudo bash provision-backend.sh` for it to work. When run as `bash provision-backend.sh`, the following error occurred:
image

**Comment by bausmeier** [comment]
@danfuterman From that output it looks like the `/opt/bsis` directory is owned by the wrong user. It should be owned by the user that you ran the script with - not root. If it is owned by root you need to change the owner or just delete the directory and run the script again.

**Pull request merged**
