### PR TITLE
refactored test code wrt to SecurityUser

### PR DESCRIPTION
**Pull request by timler**
This PR fixes the issues with the tests that randomly failed with constraint violation issues (e.g. DonationBatchCRUDServiceTests).

The issue is that the Spring Security User is not being set and unset correctly and tests are having an impact on each other.

I added methods to the various test base classes that can manage the Security User so it isn't up to every test to do it by itself (and introduce more bugs).

### CODE REVIEW

**Comment by timler** [comment]
Please see related issue: #359

**Comment by bausmeier** [comment]
Looks good to me :+1:

@jembi/bsis-developers Does this fix the failing tests for everyone?

@danfuterman Is this okay to be merged into master? It only touches test classes so it's low risk.

**Comment by danfuterman** [comment]
Thanks! It's fine to merge this into master :+1:

**Comment by debonair** [comment]
@bausmeier this works for me thanks

**Comment by bausmeier** [comment]
Hmmm. I reran the build on Travis and now it failed.

**Comment by timler** [comment]
Seems like the tests didn't fail but the process was also killed.

**Pull request merged**
