### PR TITLE
386 donor counselling modification and deletion rules

### LINKED ISSUE #386: Post-donation counselling - implement modification and deletion rules
Currently, a user is automatically flagged for post-donation counselling according to their test outcomes (see #330). Once they have been flagged, the user is able to record the outcome of the counselling (i.e. the post-donation counselling status), but they cannot edit this after the initial recording of the status. The aim of this task is to add functionality to provide for the following rules:

 - Can I edit the counseling status after saving an initial status?
  -	Yes
   -	Use case – person refuses counseling initially, and then comes back later and receives counseling
 - Can I remove a status (i.e. reflag for counseling) after saving an initial status?
  -	Yes

### PR DESCRIPTION
**Pull request by debonair**
closes #386

### CODE REVIEW

**Comment by debonair** [comment]
@danfuterman please review

**Comment by danfuterman** [comment]
@debonair - you should also request a review from @bausmeier please.

**Comment by bausmeier** [comment]
LGTM :+1:

**Comment by danfuterman** [comment]
@debonair one small issue - when I click on `Remove Status`, the Save and Cancel buttons are shown as disabled during the form submission, but the Remove Status button appears as enabled. It should also appear as disabled during form submission.

**Comment by danfuterman** [comment]
@debonair all working as expected, but can you refactor `canResetStatus` to `canRemoveStatus` to make it consistent with the original use of `Remove Status`.

**Comment by debonair** [comment]
@danfuterman fixed please review

**Pull request merged**
