### PR TITLE
refactored haemoglobin level values closes #443

### LINKED ISSUE #443: Refactor qualitative Haemoglobin values to use Pass & Fail
See #309 for original issue and code.

In the original issue, qualitative Haemoglobin values were set as:

```
   LOW("Low"),
   NORMAL("Normal"),
   HIGH("High");
```

This should be refactored to use the following options:

 - Pass
 - Fail

### PR DESCRIPTION
**Pull request by debonair**
closes #443

### CODE REVIEW

**Comment by debonair** [comment]
@jonojhs please test this on my test box

**Comment by jonojhs** [comment]
@debonair Confirmed working, however had a chat with Linda and we want to display the dropdown value next to the HB value

Display like this, just a label one space away from the HB 
image

**Comment by jonojhs** [comment]
@debonair confirmed working when the following is set to true.

image

**Comment by bausmeier** [comment]
@debonair Change looks fine, but what about the values which have already been stored? I think that there needs to be a db changeset to update them.

**Comment by debonair** [comment]
@bausmeier @danfuterman how should I do the mapping to the new values? i.e which values equate to pass and which to fail? there isn't a 1:1 relationship that I am aware of...

**Comment by bausmeier** [comment]
@debonair I would think that high and low should map to fail, and normal should map to pass, but I'm not sure. Best to get confirmation on this for Daniel or Linda.

**Comment by debonair** [comment]
@lindajembi what do you think?

**Comment by debonair** [comment]
@danfuterman please give your input here, how should existing values be handled?

**Comment by danfuterman** [comment]
@debonair - You can go with Brett's suggestion - High/Low map to fail, Normal maps to Pass.

**Comment by debonair** [comment]
@bausmeier please review

**Pull request merged**
