### PR TITLE
BSIS-794: As a component lab staff user I need to be able to record the receipt of donations as part of a component batch.

### PR DESCRIPTION
**Pull request by timler**
See https://jembiprojects.jira.com/browse/BSIS-794

### CODE REVIEW

**Comment by timler** [comment]
I implement the 3 tickets together (sorry), and when I tried to commit separately it did not work out as I hoped it would, but it is now compiling and the tests are passing.

Code coverage will increase once we add the new Repositories and test those.

**Comment by bausmeier** [comment]
@timler I see that the new permissions for component batches haven't been added to the database yet. Just pointing it out in case you forgot (I know that you are still working on those tickets).

**Comment by timler** [comment]
@bausmeier I have added the permissions now (fdcf481)

**Comment by bausmeier** [comment]
@timler I've been through all of the commits for BSIS-835 and just left a few comments.

**Comment by timler** [comment]
@lauravignoli I finished my review of your ticket BSIS-919. It looks good and I only noticed the following things:
 - the table isn't 100% maximised on the screen
 - the donation status is displaying true/false
 - the dates are not formatted in the PDF and CSV

I do have a usability concern about the navigation after viewing an item from the list the user needs to use the back button to return to the search but the form is reset and the search results gone. However, this problem exists for the search on DonationBatch and TestBatch so this should be investigated as part of that (and probably after some user testing).

**Pull request merged**
