### PR TITLE
Account recovery 285

### LINKED ISSUE #285: Account Recovery Feature
Add functionality to allow a user to recover their account/reset their password, when they forget their username or password.

The password should be reset and this information sent to the user's email address.

*Currently, a user's email address is not mandatory, but with this feature, it should probably be updated to be a mandatory field.

### PR DESCRIPTION
**Pull request by bausmeier**
For the email sending to work SMTP credentials need to be added to the `email.properties` file. The easiest option is to use Gmail and just add in the account's username and password.

Closes #285.

### CODE REVIEW

**Comment by danfuterman** [comment]
Tested initial functionality, working as expected.

**Comment by bausmeier** [comment]
@danfuterman Please review.

**Comment by danfuterman** [comment]
@bausmeier I resolved the compilation issues by configuring maven to use Java 1.7.x.
I think we should update the maven-compiler `<source>` and `<target>` values in `pom.xml` to use 1.7, to imply that Java 1.7 is required. 

i.e. change from:

```
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
```

to:


```
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
```

**Comment by bausmeier** [comment]
@danfuterman Done.

**Comment by danfuterman** [comment]
Great! @timler & @debonair - please take note of https://github.com/jembi/bsis/commit/a85d61717f7d8bc08696fcca7be95b622987323e just in case - on the slim chance that you're using a version of Java < 1.7, this might cause some issues for you once this PR is merged.

**Comment by debonair** [comment]
@danfuterman I am using Java 1.8 so its all working fine for me.

**Pull request merged**
