### PR TITLE
Audit revisions endpoint 323

### LINKED ISSUE #323: Backend provisions to view changelog

### PR DESCRIPTION
**Pull request by bausmeier**
Adds an endpoint for fetching audit revisions to display in the changelog.

Closes #323.

### CODE REVIEW

**Comment by bausmeier** [comment]
The SQL script for migrating existing databases can be found here: https://gist.github.com/bausmeier/bd05d409f6b2e3b4d754.

**Comment by bausmeier** [comment]
Finally got a useful stack trace for the failing test.

```
Expected: is <DefaultRevisionEntity(id = 12, revisionDate = Aug 4, 2015 3:19:05 PM)>
     got: <DefaultRevisionEntity(id = 10, revisionDate = Aug 6, 2015 3:19:05 PM)>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:21)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at repository.AuditRevisionRepositoryTests.testFindRecentAuditRevisions_shouldReturnAuditRevisionsOrderedByTimestamp(AuditRevisionRepositoryTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.apache.maven.surefire.junitcore.ClassDemarcatingRunner.run(ClassDemarcatingRunner.java:58)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:62)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
```

**Comment by bausmeier** [comment]
Adding an extra assertion I get:

```
Expected: is <2>
     got: <12>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:21)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at repository.AuditRevisionRepositoryTests.testFindRecentAuditRevisions_shouldReturnAuditRevisionsOrderedByTimestamp(AuditRevisionRepositoryTests.java:49)
```

So something is creating extra revisions or a test is not cleaning up after itself.

**Comment by danfuterman** [comment]
@bausmeier - this looks like it's related to the issues that @timler recently identified - https://github.com/jembi/bsis/issues/318#issuecomment-127041103. Those issues will be addressed in the unit test task, so in the interest of getting this work merged in, I'd suggest adding `@Ignore` to the problem test(s), and we can address those once the unit test issues have been resolved. Sound good to you?

**Comment by timler** [comment]
@bausmeier If you want to check if the issue I found was causing the unit test to fail, add `@Transactional` to the `DonorRepositoryTest`. Also ensure that your test is running in a transaction by adding the same annotation (it can be declared on a class or method level) in order to have inserted/updated data cleaned up after the test is finished

**Comment by bausmeier** [comment]
Thanks @timler, that looks like it the same issue. I won't make the same changes on this branch in case it causes merge conflicts. I will just unignore the tests once both branches have been merged.

@danfuterman Please review.

**Comment by timler** [comment]
Please note that the changes to the ddl_mysql.sql file will cause problems when we upgrade the Lesotho database. We will need to write some SQL to upgrade that database manually.

**Pull request merged**
