### PR TITLE
Ensure consistent dates throught the API

### PR DESCRIPTION
**Pull request by debonair**
@danfuterman please review this pull request
See #278

### CODE REVIEW

**Comment by danfuterman** [comment]
@debonair - Feedback from some end-to-end testing:

- Issue adding donation when adding directly from the donation batch UI (Donors -> Manage Clinic):

```
{"hasErrors":"true","developerMessage":"Error parsing  Json request to corresponding object. please form the correct JSON String ","userMessage":"","errorCode":"BAD_REQUEST","moreInfo":"Could not read JSON: Can not construct instance of long from String value '06/22/2015': not a valid Long value\n at [Source: java.io.PushbackInputStream@5163d072; line: 1, column: 29] (through reference chain: backingform.CollectedSampleBackingForm[\"collectedOn\"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value '06/22/2015': not a valid Long value\n at [Source: java.io.PushbackInputStream@5163d072; line: 1, column: 29] (through reference chain: backingform.CollectedSampleBackingForm[\"collectedOn\"])"}
```

- For new donors, the 'Due To Donate' field is being set to `January 1, 1970`, rather than being empty/null.

- Issue when adding a deferral (Donors -> Manage Donors):

```
{"hasErrors":"true","developerMessage":"Error parsing  Json request to corresponding object. please form the correct JSON String ","userMessage":"","errorCode":"BAD_REQUEST","moreInfo":"Could not read JSON: Can not construct instance of long from String value '06/25/2015': not a valid Long value\n at [Source: java.io.PushbackInputStream@4ee01f95; line: 1, column: 2] (through reference chain: backingform.DeferralBackingForm[\"deferredUntil\"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value '06/25/2015': not a valid Long value\n at [Source: java.io.PushbackInputStream@4ee01f95; line: 1, column: 2] (through reference chain: backingform.DeferralBackingForm[\"deferredUntil\"])"}
```

- Issue when trying to update (PUT) a donation:
```
{"hasErrors":"true","developerMessage":"Error parsing  Json request to corresponding object. please form the correct JSON String ","userMessage":"","errorCode":"BAD_REQUEST","moreInfo":"Could not read JSON: Can not construct instance of long from String value '06/22/2015': not a valid Long value\n at [Source: java.io.PushbackInputStream@76d0da62; line: 1, column: 294] (through reference chain: backingform.CollectedSampleBackingForm[\"collectedOn\"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value '06/22/2015': not a valid Long value\n at [Source: java.io.PushbackInputStream@76d0da62; line: 1, column: 294] (through reference chain: backingform.CollectedSampleBackingForm[\"collectedOn\"])"} 
```

- Issue when trying to load the page - Donors -> View/Export Donor List (this seems to be an issue with the front-end PR changes, but I'm adding the comment here):
```
$rootScope is not defined
    at new <anonymous> (http://127.0.0.1:9000/scripts/controllers/donors.js:699:25)
```

- Issue when trying to search for Components and Discards (different UIs, same root issue) - 
Components -> Find Components 
&
Components -> Find Discards:

   - When search date fields are empty:  NullPointer Exception related to `donationDateFrom` and `donationDateTo`:
```
{"hasErrors":"true","developerMessage":"Null Pointer Exception: controller.ProductController.findProductPagination(ProductController.java:201)","userMessage":"","errorCode":"INTERNAL_SERVER_ERROR","moreInfo":{"methodName":"findProductPagination","fileName":"ProductController.java","lineNumber":201,"className":"controller.ProductController","nativeMethod":false}}
```

   - When search fields are not empty (i.e. specify dates):
```
{"hasErrors":"true","developerMessage":"value '06/04/2015' is not compatable toclass java.lang.Long","userMessage":"Please check thr input  value '06/04/2015'","errorCode":"BAD_REQUEST","moreInfo":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"06/04/2015\""}
```

- Issue with dates after changing the general configs properties to use `dd/MM/yyyy` rather than `MM/dd/yyyy` - e.g. tried to add a Donor with DOB 19 November 1976, but this appeared as `03/01/1970` after adding the donor.

- NB.: in general, when making changes, try to test related endpoints - not just adding (POST) and retrieving (GET), but also updating (PUT) and deleting to make sure the changes don't cause issues with those.

**Comment by danfuterman** [comment]
@debonair - can you address these issues?

**Comment by debonair** [comment]
@danfuterman am suspending the work on roles and taking a look at this morning.

**Comment by debonair** [comment]
I changed nothing in this pull request, all the errors were being caused by the front end sending incorrectly formatted dates, please pull the related frontend branch and re test.

**Comment by debonair** [comment]
This pull request is being dropped in favour of #280

**Pull request closed without merging**
