### PR TITLE
added sheduled task to update the general config at startup

### PR DESCRIPTION
**Pull request by debonair**
@danfuterman Please take a look at my initial solution for updating the general config values, while I add the default values to the liquibase file

### CODE REVIEW

**Comment by debonair** [comment]
@danfuterman please review

**Comment by danfuterman** [comment]
@debonair - two suggestions:

 - it would be great if dataType could be specified by name, rather than the full json dataType. i.e.:
this: 
```
       {
           "datatype": "text"
           "description": "Example Property Description",
           "name": "examplePropertyName",
           "value": "exampleValue"
        }
```
would be better than the current way:
```
          {
           "dataType": {
               "id": 1,
               "datatype": "text"
           },
           "description": "Example Property Description",
           "name": "examplePropertyName",
           "value": "exampleValue"
        }
```

 - I'd suggest improving the error handling and feedback. 1. Is it possible to get the logging to output on the mvn command line build, so that the status and outcomes are displayed when compiling the app? 2. It would be great to include the following logging:
  - when the configs.json file can't be found or opened - display a message to say something like 'no config file found, default values used'.
  - when a config property is successfully added or updated, display a relevant message along with the name of the property.
  - when a config property is unsuccessfully added or updated (because of an issue with the json or values etc.) - display a relevant message along with the name of the property.
 - Q. What happens if the json is not formatted correctly - will it just affect that property, will it affect the properties after that, or will it cause the whole thing to fail?

**Comment by debonair** [comment]
@danfuterman as it stands the values can only be updated when you deploy the war,
maven only packages the json config with the application and it is read and executed at run time. I don't see how I can add maven logging to this.

As for error handling, I can definitely improve that as you suggested as well as simplify how you specify the data type, i.e remove the id bit, and find the dataType by name rather and associate that to the config.

I will also test with malformed JSON and see what happens

**Comment by danfuterman** [comment]
Okay sure, that makes sense. One more thing - is it possible to place the file in the /src directory, so that it's in the same directory as the other db/swagger etc. properties files?

**Comment by debonair** [comment]
OK cool

**Comment by debonair** [comment]
@danfuterman please review

**Comment by danfuterman** [comment]
@debonair - you were going to look into the impact of json formatting issues - "What happens if the json is not formatted correctly - will it just affect that property, will it affect the properties after that, or will it cause the whole thing to fail?"
Can you feedback on that before I review?

**Comment by debonair** [comment]
if the JSON is not correctly formatted, it throws a JsonSyntaxException and the update does not continue.

**Comment by danfuterman** [comment]
Can you clarify if this happens before attempting to run the update, or during?
I.e. if the 3rd property has JSON that is formatted incorrectly:
 - do the first 2 properties before that still get updated?
 - or does the whole thing fail and no properties are updated?

**Comment by debonair** [comment]
The whole thing fails before any properties get updated.

**Comment by debonair** [comment]
Basically what happens, is that I read the file and try to parse it using gson, if the parse fails nothing gets updated and the relevant exceptions are thrown. However, If there are no proplems the code loops throu the genated array and updates each property in turn id the property exists, or creates a new propertu.The code is quite self explanatory.

**Pull request merged**
