### PR TITLE
Test Batches – implement modification and deletion rules

### LINKED ISSUE #380: Test Batches – implement modification and deletion rules
Currently, a user can add a Test Batch, but they cannot edit, delete or reopen the batch. The aim of this task is to add this functionality, and ensure the rules associated with this are in place.

-	Can I add or remove donation batches to a test batch after it has been created?
  -	Yes, if no test outcomes/results or anything has been recorded.
  -	If using worksheets, the cutoff point would be once the worksheet(s) have been printed – can no longer add or remove donation batches.
-	Can I add or remove donation batches to a test batch after it has been created and test results have been recorded?
  -	No
-	Can I delete a test batch? Only if no results have been recorded
-	What can I edit in a test batch?
  -	Location
  -	Date
-	Can I re-open a test batch?
  -	Yes 
  -	What are the rules on this? - similar to donation batch, whatever rules were relevant to the initial open batch would still apply now – i.e. no differentiation between an open batch and a batch that has been re-opened.
  -	Can I edit test outcomes
   -	Yes
  -	Can I edit test results when I reopen a batch? – If I can do it before I closed the batch
-	Can I edit the original test outcomes if confirmatory/screening results have been added for that test?
  -	No

### PR DESCRIPTION
**Pull request by timler**
closes #380

branch created from 373-test-batch-release-2

### CODE REVIEW

**Comment by timler** [comment]
To review: f366a4f

**Comment by timler** [comment]
@bausmeier want me to deal with the merge conflicts?

**Comment by bausmeier** [comment]
Yes please. Trying to get the test batch release PR finished and merged so that this one is easier to review.

**Comment by timler** [comment]
@bausmeier looks good after the merge.

**Comment by danfuterman** [comment]
@bausmeier - Following up on this to confirm you'll be testing this now that the batch release task has been merged? It seems there are some new merge conflicts that need to be resolved, could you try look into that as part of your review?

**Comment by bausmeier** [comment]
@danfuterman Yip. I will try and merge in the latest master and review the changes.

**Comment by danfuterman** [comment]
Thanks!

**Comment by bausmeier** [comment]
@timler I have merged in the latest master which includes the test batch release changes. Please update this PR to handle the new TestBatch.RELEASED status in the constraint checks.

One issue that I noticed is that you include the permissions in the test batch view model based on the constraints, but you don't check the constraints in the code that actually deletes or updates the test batches. I haven't tested the functionality yet, but other than that the code looks good.

**Comment by danfuterman** [comment]
@timler - #411 may have caused some new merge conflicts with this PR, let me know if you need some info on what was done there and if there are any uncertainties on how to resolve the conflicts.

**Comment by timler** [comment]
@danfuterman I have merged in trunk see 6f596cb

@bausmeier I have made the suggested changes and added some more tests. See 727d5ea

**Comment by bausmeier** [comment]
@timler Just left some minor feedback, otherwise it looks good.

**Comment by timler** [comment]
@bausmeier Did the two changes you highlighted and also changed the constraints for putting the batch into RELEASED status after reopening it. See 41d7eee

**Comment by bausmeier** [comment]
This PR looks good to me. I don't think that any of the feedback on the frontend PR relates to this, so I am happy if you go ahead and do a final review @danfuterman.

**Comment by timler** [comment]
In fixing a bug, I to make some changes to the validator for test batch. Please see 6ccd520. Thanks

**Pull request merged**
