### PR TITLE
fixed general config update

### PR DESCRIPTION
**Pull request by debonair**
@danfuterman please review, this works with /bsis-frontend/pull/115

### CODE REVIEW

**Comment by danfuterman** [comment]
@debonair - For consistency, I'd suggest adding a `copy()` method to `GeneralConfig.java`, and then calling that method, rather than doing this directly in the Repository method. For example, look at `User.copy()`:
```
  public void copy(User user) {
    this.username = user.getUsername();
    this.firstName = user.getFirstName();
    this.lastName = user.getLastName();
    this.emailId = user.getEmailId();
    this.isAdmin = user.getIsAdmin();
    this.isActive = user.getIsActive();
    this.roles = user.getRoles();
  }
```

**Comment by danfuterman** [comment]
Relates to https://github.com/jembi/bsis-frontend/issues/112

**Comment by debonair** [comment]
@danfuterman please review the refatored code

**Comment by danfuterman** [comment]
:+1:

**Pull request merged**
